puts 'The students of my cohort at Makers Academy'
puts '-------------------------------------------'
puts 'Bruce Steedman'
puts 'James Brooke'
puts 'Chis..'
puts 'Hannah..'
puts 'Laura..'
puts 'Jeremy Marer'
puts 'Kennedy..'
puts 'Simon..'
puts 'Tom..'
puts 'Tom..'
puts 'Giacomo..'
puts 'Annette..'
puts 'Asta..'
puts 'Kumi..'
puts 'Nisar..'
puts 'Georgi..'
puts 'Peter..'
puts 'Jean-Baptiste..'
